[phases.setup]
nixPkgs = ['nodejs-18_x', 'bash']

[phases.install]
cmds = [
  'cd server && npm ci --prefer-offline --no-audit',
  'cd ../client && npm ci --prefer-offline --no-audit'
]

[phases.build]
cmds = [
  'cd client && npm run build'
]

[start]
cmd = 'cd server && npm start'
